{
  "hash": "a49c449103ead8a19e45e762127d08f2",
  "result": {
    "engine": "knitr",
    "markdown": "# Describing a dataset\n\n\n\n## When to use it\n\nUse this chapter before analysis: inspect the data, question what you find, and\nbuild the dictionary that records the cohort you actually received. This is\ndataset reconnaissance, not the publication table itself.\n\nStart with `proc_contents()` to inventory the variables and their missingness,\nthen use `proc_means()` to inspect the numeric distributions.\n`data_dictionary()` turns that inventory into the one-page artifact you hand a\ncollaborator. These are R-side checks, and none produces a table anybody will\npublish. You run them because you cannot decide what belongs in Table 1 until\nyou know what you are holding: which variables are there, what type each one\ncame in as, and how much of each is actually populated.\n\nFor readers moving an older workflow to R, the first two names are migration\nlandmarks for the retired `PROC CONTENTS` and `PROC MEANS` steps. That is this\nrecipe: the *pre-analysis* table, the one that runs before the Table 1 in the\n[publication tables](qt_tables.qmd) chapter has a shape.\n\nReach for it whenever a dataset is new to you, has just been re-extracted, or\narrives with someone telling you it is \"the same as last time.\" Ten seconds of\n`proc_contents()` catches the variable that came back as character this quarter,\nor the one that is four-fifths missing, while it is still cheap to ask about.\n\n## The data it needs\n\nAny data frame. Labels, when the columns carry them, are picked up and\nreported; unlabelled columns fall back to the variable name. We use\n`generate_survival_data()`, the same simulated cohort the\n[publication tables](qt_tables.qmd) chapter builds its Table 1 from, so you can\nread the two chapters against one dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndta <- hvtiRutilities::generate_survival_data(n = 200, seed = 42)\ndim(dta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 200  24\n```\n\n\n:::\n:::\n\n\n## Build it\n\n### What is in this dataset: `proc_contents()`\n\n`proc_contents()` prints what SAS prints: a header carrying the observation and\nvariable counts, then one row per variable with its creation position, name, SAS\ntype, format, and label. Next to those it adds three columns you would otherwise\ngo looking for separately: `class`, the R type sitting behind the SAS one;\n`n_unique`, how many distinct values the column holds; and `pct_missing`, how\nmuch of it is empty.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc_contents(dta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObservations: 200\nVariables:    24\n\n   num     variable type format                                          label\n1    8          age  Num   <NA>                         Age at surgery (years)\n2   10          bmi  Num   <NA>                        Body mass index (kg/m2)\n3   20  bypass_time  Num   <NA>              Cardiopulmonary bypass time (min)\n4    1        ccfid Char   <NA>                                     Patient ID\n5    5         dead  Num   <NA>           Death indicator (1=dead, 0=censored)\n6   23     diabetes Char   <NA>                              Diabetes mellitus\n7   14       gfr_bs  Num   <NA>                  Baseline eGFR (mL/min/1.73m2)\n8   11       hgb_bs  Num   <NA>                     Baseline hemoglobin (g/dL)\n9   24 hypertension Char   <NA>                                   Hypertension\n10   4      iv_dead  Num   <NA>                Follow-up time to death (years)\n11   3     iv_opyrs  Num   <NA> Observation interval (years) since origin_year\n12   7      iv_reop  Num   <NA>          Follow-up time to reoperation (years)\n13  15     lvefvs_b  Num   <NA>              Baseline LV ejection fraction (%)\n14  16     lvmass_b  Num   <NA>                           Baseline LV mass (g)\n15  17      lvmsi_b  Num   <NA>                  Baseline LV mass index (g/m2)\n16  22   nyha_class Char   <NA>                          NYHA functional class\n17   2  origin_year  Num   <NA>                 Calendar year for iv_opyrs = 0\n18  13     plate_bs  Num   <NA>                 Baseline platelet count (K/uL)\n19   6         reop  Num   <NA>                      Reoperation (1=yes, 0=no)\n20   9          sex Char   <NA>                                            Sex\n21  19     stvold_b  Num   <NA>          Baseline SV index - diastolic (mL/m2)\n22  18     stvoli_b  Num   <NA>           Baseline SV index - systolic (mL/m2)\n23  12       wbc_bs  Num   <NA>                      Baseline WBC count (K/uL)\n24  21  xclamp_time  Num   <NA>                  Aortic cross-clamp time (min)\n       class n_unique pct_missing\n1    numeric      165         0.0\n2    numeric      123         0.0\n3    numeric      100         0.0\n4  character      200         0.0\n5    integer        2         0.0\n6     factor        2         0.0\n7    numeric      174         0.0\n8    numeric       66         0.0\n9     factor        2         0.0\n10   numeric      184         0.0\n11   numeric      183         0.0\n12   numeric       31        83.5\n13   numeric      149         0.0\n14   numeric      191         0.0\n15   numeric        1         0.0\n16   ordered        4         0.0\n17   integer       21         0.0\n18   numeric      135         0.0\n19   integer        2         0.0\n20    factor        2         0.0\n21   numeric      171         0.0\n22   numeric      168         0.0\n23   numeric      172         0.0\n24   numeric       75         0.0\n```\n\n\n:::\n:::\n\n\nVariables come back sorted alphabetically, matching SAS's *Alphabetic List of\nVariables and Attributes*. Pass `order = \"varnum\"` for creation order instead.\nThe `num` column reports creation position either way, so the original order is\nalways recoverable by eye.\n\nTwo columns repay a slow read. `type` is deliberately two-valued, `Char` or\n`Num`, because that is all SAS storage offers: `sex` is a factor in R and\nreports `Char` here, while `class` keeps the R truth alongside it. Then\n`pct_missing`, which is where the surprises live. Here 23 of the 24 variables\nare complete and `iv_reop` is 83.5% missing, which is exactly right for a\nreoperation follow-up time. It exists only for the 33 patients who had a\nreoperation. Missingness with a reason is structure; missingness you cannot\naccount for is a question for whoever built the extract.\n\n### What the numbers look like: `proc_means()`\n\n`proc_means()` summarises the numeric columns you name, defaulting to SAS's own\ndefault five statistics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc_means(dta, vars = c(\"age\", \"bmi\", \"gfr_bs\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  variable                         label   n    mean       std  min   max\n1      age        Age at surgery (years) 200 44.5890 14.595538  1.0  85.0\n2      bmi       Body mass index (kg/m2) 200 26.7885  4.750479 15.0  41.8\n3   gfr_bs Baseline eGFR (mL/min/1.73m2) 200 76.1505 19.392901 25.9 120.0\n```\n\n\n:::\n:::\n\n\nOmit `vars` and every numeric column is analysed, the way `PROC MEANS` behaves\nwith no `VAR` statement. `stats =` takes the SAS keywords you already know,\nincluding `\"median\"`, `\"q1\"`, `\"q3\"`, `\"nmiss\"`, `\"stderr\"`, and any `\"pNN\"`\npercentile.\n\nQuantiles are worth one note. They use `stats::quantile(type = 2)`, which is the\nR equivalent of SAS's `QNTLDEF=5`, not R's own `type = 7` default. On a large\nsample the two agree. On the small, even-numbered subgroups a clinical\nstratification hands you, they do not: for `c(1, 2, 3, 4)` the first quartile is\n1.5 in SAS and 1.75 under R's default. The median agrees, which is how the\ndisagreement stays hidden.\n\n### Stratified by a class variable\n\nGive it `class =` and you get the same table once per group, the `CLASS`\nstatement by another name.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc_means(dta, vars = c(\"age\", \"bmi\"), class = \"sex\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sex variable                   label   n     mean       std  min  max\n1 Female      age  Age at surgery (years)  77 45.07143 14.800443  1.0 79.3\n2   Male      age  Age at surgery (years) 123 44.28699 14.518428  8.4 85.0\n3 Female      bmi Body mass index (kg/m2)  77 27.05325  4.889747 17.4 41.8\n4   Male      bmi Body mass index (kg/m2) 123 26.62276  4.673729 15.0 39.1\n```\n\n\n:::\n:::\n\n\nRows sort by analysis variable first, then by class level, so you read a\nvariable's groups down the page rather than hunting across. A factor class\nvariable orders by its declared levels rather than alphabetically, matching\nSAS's `ORDER=INTERNAL`, which is what keeps an ordered clinical scale in\nclinical sequence.\n\nCheck the `n` column against your cohort size. Rows with a missing value in any\nclass variable are dropped, again matching SAS, so a total that comes up short\ntells you how many patients had no group to sit in. Here 77 and 123 add to 200,\nand nothing was dropped.\n\n### The whole dictionary: `data_dictionary()`\n\n`data_dictionary()` is `proc_contents()` in creation order with the SAS-storage\ncolumns dropped and a summary put in their place. Out go `num`, `type`, and\n`format`, which describe how a value is stored rather than what it is. In comes\na compact `summary` giving min, median, and max for a numeric variable, the\nlevels for a factor, the TRUE percentage for a logical. That leaves six columns:\n`variable`, `label`, `class`, `n_unique`, `pct_missing`, and `summary`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_dictionary(dta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 variable                                          label\nccfid               ccfid                                     Patient ID\norigin_year   origin_year                 Calendar year for iv_opyrs = 0\niv_opyrs         iv_opyrs Observation interval (years) since origin_year\niv_dead           iv_dead                Follow-up time to death (years)\ndead                 dead           Death indicator (1=dead, 0=censored)\nreop                 reop                      Reoperation (1=yes, 0=no)\niv_reop           iv_reop          Follow-up time to reoperation (years)\nage                   age                         Age at surgery (years)\nsex                   sex                                            Sex\nbmi                   bmi                        Body mass index (kg/m2)\nhgb_bs             hgb_bs                     Baseline hemoglobin (g/dL)\nwbc_bs             wbc_bs                      Baseline WBC count (K/uL)\nplate_bs         plate_bs                 Baseline platelet count (K/uL)\ngfr_bs             gfr_bs                  Baseline eGFR (mL/min/1.73m2)\nlvefvs_b         lvefvs_b              Baseline LV ejection fraction (%)\nlvmass_b         lvmass_b                           Baseline LV mass (g)\nlvmsi_b           lvmsi_b                  Baseline LV mass index (g/m2)\nstvoli_b         stvoli_b           Baseline SV index - systolic (mL/m2)\nstvold_b         stvold_b          Baseline SV index - diastolic (mL/m2)\nbypass_time   bypass_time              Cardiopulmonary bypass time (min)\nxclamp_time   xclamp_time                  Aortic cross-clamp time (min)\nnyha_class     nyha_class                          NYHA functional class\ndiabetes         diabetes                              Diabetes mellitus\nhypertension hypertension                                   Hypertension\n                 class n_unique pct_missing\nccfid        character      200         0.0\norigin_year    integer       21         0.0\niv_opyrs       numeric      183         0.0\niv_dead        numeric      184         0.0\ndead           integer        2         0.0\nreop           integer        2         0.0\niv_reop        numeric       31        83.5\nage            numeric      165         0.0\nsex             factor        2         0.0\nbmi            numeric      123         0.0\nhgb_bs         numeric       66         0.0\nwbc_bs         numeric      172         0.0\nplate_bs       numeric      135         0.0\ngfr_bs         numeric      174         0.0\nlvefvs_b       numeric      149         0.0\nlvmass_b       numeric      191         0.0\nlvmsi_b        numeric        1         0.0\nstvoli_b       numeric      168         0.0\nstvold_b       numeric      171         0.0\nbypass_time    numeric      100         0.0\nxclamp_time    numeric       75         0.0\nnyha_class     ordered        4         0.0\ndiabetes        factor        2         0.0\nhypertension    factor        2         0.0\n                                                                  summary\nccfid        200 levels: PT00001, PT00002, PT00003, PT00004, PT00005, ...\norigin_year                                            1998 / 2008 / 2018\niv_opyrs                                              1.06 / 7.87 / 14.99\niv_dead                                                0.25 / 4.1 / 13.98\ndead                                                            0 / 1 / 1\nreop                                                            0 / 0 / 1\niv_reop                                                0.04 / 1.29 / 9.92\nage                                                        1 / 44.75 / 85\nsex                                                2 levels: Female, Male\nbmi                                                     15 / 26.65 / 41.8\nhgb_bs                                                      7.6 / 13 / 18\nwbc_bs                                                 1.5 / 7.35 / 15.53\nplate_bs                                                   50 / 225 / 447\ngfr_bs                                                 25.9 / 75.75 / 120\nlvefvs_b                                                29.1 / 53.75 / 75\nlvmass_b                                               60 / 184.4 / 377.2\nlvmsi_b                                                      40 / 40 / 40\nstvoli_b                                               20.5 / 53.7 / 90.3\nstvold_b                                               40 / 93.35 / 153.6\nbypass_time                                               20 / 88.5 / 194\nxclamp_time                                                 13 / 57 / 118\nnyha_class                                       4 levels: I, II, III, IV\ndiabetes                                                2 levels: No, Yes\nhypertension                                            2 levels: No, Yes\n```\n\n\n:::\n:::\n\n\nThat summary column is what makes the table hand-off-able, and it is also where\ndegenerate variables announce themselves. `lvmsi_b` reads `40 / 40 / 40` with an\n`n_unique` of 1, so it is a constant. A constant costs a row in Table 1 and\ntells the reader nothing. Send this frame through `write.csv()` and you have the\ndata-dictionary appendix a protocol or a data-sharing agreement asks for.\n\n## Read it\n\nThree outputs, three questions.\n\n`proc_contents()` answers *what is here*: names, types, labels, and how complete\neach column is. Read it top to bottom once, then read `pct_missing` on its own,\ncolumn-first rather than row-first. That single pass is most of the value.\n\n`proc_means()` answers *what do the numbers look like*: centre, spread, and\nrange per variable, and per group once you add `class =`. Read `min` and `max`\nbefore you read the mean. Impossible values show up at the ends, and a mean is\ngood at hiding one. The `age` minimum of 1 in this simulated cohort is the kind\nof thing you would query on real data.\n\n`data_dictionary()` answers *what do I hand someone else*. It is the one of the\nthree you save to a file, and the [data governance](data_governance.qmd) chapter\nfiles it beside the manifest for exactly that reason. Read it column by column,\nwith most of the attention on `pct_missing` and `n_unique`. High missingness\nflags a variable you cannot lean on without saying so. A distinct-value count\nthat surprises you, two levels where you expected continuous or a thousand where\nyou expected a category, usually means a typing or coding problem upstream,\ncaught here before it reaches a model. The `summary` column is your sanity check\non range: a negative age or an ejection fraction above 100 shows up immediately.\n\nNone of the three is a publication table. They are the reconnaissance you do\nbefore deciding what the publication table should contain, and\n[Table 1](qt_tables.qmd) comes after.\n\n## Pitfalls\n\n- **`pct_missing` is `NaN`, not `0`, when the frame has no rows.** Filter a\n  cohort down to nothing and every `pct_missing` comes back `NaN`, because\n  `mean(is.na(x))` over an empty vector is 0/0. The table looks broken and is\n  in fact reporting honestly: the proportion of missing values among no values\n  is undefined, and a `0` there would assert that nothing is missing. If you\n  format the column for display, handle `NaN` explicitly rather than letting it\n  print raw next to real percentages, and treat it as the signal it is that your\n  filter removed everything.\n\n- **`class =` groups on the stored value, not the printed one.** Two values that\n  render identically but differ underneath stay separate groups, and you get\n  back two rows that look like duplicates of each other. A trailing space in a\n  character code does it, and so does a numeric group variable whose values\n  differ below print precision. The behaviour is correct, since grouping on the\n  rendered string would quietly merge values that are genuinely distinct, but it\n  will mislead you if you are diagnosing from printed output alone. When a group\n  count looks doubled, run `unique()` or `table()` on the class variable and\n  compare what you get to what the table showed you.\n",
    "supporting": [
      "data_tables_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}