{
  "hash": "ea2c05fdc78b5c0d8de48c964627544c",
  "result": {
    "engine": "knitr",
    "markdown": "# Tables that accompany figures\n\n\n\nMany manuscript figures are paired with a small numeric table: a\nnumbers-at-risk strip below a Kaplan-Meier curve, or the count panel\nbeneath a longitudinal participation bar chart. The `hvtiPlotR` plot\nobjects carry these companion tables alongside the plot data, so we can\npull the numbers straight out and render them with `gt` [@R-gt], the\nright tool, as in the [publication tables](qt_tables.qmd) chapter, when a\ntable's destination is this book or another HTML document.\n[Manuscript tables](hv_tables.qmd) headed for a Word file go through\n`hvtiRtables` instead, which turns a `gtsummary` summary into a CORR-compliant\nflat-header table.\n\n## When to use it\n\nA figure shows the shape of a result; the companion table gives the reader the\nnumbers the shape rests on. The two go together when a curve hides how much data\nbacks each region of it. The clearest case is the numbers-at-risk strip beneath\na Kaplan-Meier curve: the curve might look confident out at ten years, but if\nonly eight patients remain at risk there, the at-risk row is what tells the\nreader to read that tail with caution. Reach for a companion table whenever the\nfigure invites a question the plot cannot answer on its own (\"based on how\nmany?\") and you want the answer on the same page rather than buried in the text.\n\nThe at-risk count is a denominator, not a second estimate. At time $t$ it counts\npatients who are still observed and event-free immediately before $t$. An event\nchanges the survival curve and removes that patient from later risk sets;\ncensoring removes a patient from later risk sets without creating a survival\nstep. Thus the count tells you how much information supports $S(t)$ and its\nconfidence interval, but it does not tell you the survival probability by\nitself.\n\nWe work through two cases the package already supports: the at-risk strip that a\nsurvival curve needs beside it, and the participation counts that sit beneath a\nlongitudinal bar chart. In both, the numbers already live on the plot object, so\nwe never recompute them and risk a table that disagrees with its own figure.\n\n## Numbers at risk\n\n`hv_survival()` stores its companion tables in the object's `$tables`\nslot. The numbers-at-risk strip lives in `$tables$risk` (one row per\nstrata × report-time) and the per-time-point summary in `$tables$report`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm <- hv_survival(\n  sample_survival_data(n = 500, seed = 42),\n  report_times = seq(0, 20, 5)\n)\nnames(km$tables)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"risk\"   \"report\"\n```\n\n\n:::\n\n```{.r .cell-code}\nkm$tables$risk\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  strata report_time n.risk\n1    All           0    500\n2    All           5    411\n3    All          10    321\n4    All          15    259\n5    All          20    207\n```\n\n\n:::\n:::\n\n\nWe render the at-risk table directly with `gt`, relabelling the columns\nfor presentation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm$tables$risk |>\n  gt() |>\n  tab_header(\n    title = \"Numbers at Risk\",\n    subtitle = \"Patients remaining under follow-up at each report time\"\n  ) |>\n  cols_label(\n    strata      = \"Stratum\",\n    report_time = \"Time (years)\",\n    n.risk      = \"At risk (n)\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Numbers at Risk\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Patients remaining under follow-up at each report time\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrr}\n\\toprule\nStratum & Time (years) & At risk (n) \\\\ \n\\midrule\\addlinespace[2.5pt]\nAll & 0 & 500 \\\\ \nAll & 5 & 411 \\\\ \nAll & 10 & 321 \\\\ \nAll & 15 & 259 \\\\ \nAll & 20 & 207 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nThe companion report table carries the survival estimates and confidence\nlimits at the same report times. It lets you quote a 5- or 10-year estimate\ntogether with the denominator that supports it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm$tables$report |>\n  gt() |>\n  tab_header(title = \"Survival Estimates at Report Times\") |>\n  cols_label(\n    strata      = \"Stratum\",\n    report_time = \"Time (years)\",\n    surv        = \"S(t)\",\n    lower       = \"95% LCL\",\n    upper       = \"95% UCL\",\n    n.risk      = \"At risk\",\n    n.event     = \"Events\"\n  ) |>\n  fmt_number(columns = c(surv, lower, upper), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Survival Estimates at Report Times\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrrr}\n\\toprule\nStratum & Time (years) & S(t) & 95\\% LCL & 95\\% UCL & At risk & Events \\\\ \n\\midrule\\addlinespace[2.5pt]\nAll & 0 & 1.000 & 1.000 & 1.000 & 500 & 0 \\\\ \nAll & 5 & 0.822 & 0.786 & 0.853 & 412 & 1 \\\\ \nAll & 10 & 0.642 & 0.599 & 0.683 & 322 & 1 \\\\ \nAll & 15 & 0.518 & 0.474 & 0.562 & 260 & 1 \\\\ \nAll & 20 & 0.414 & 0.372 & 0.458 & 207 & 0 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nFor the figure itself, build the curve and the risk panel from that same `km`\nobject. `hv_atrisk_compose()` reads the finished curve's x-range and applies it\nto the table, so the 0-, 5-, 10-, 15-, and 20-year counts sit directly beneath\ntheir curve positions. This is why the report times and axis breaks are set to\nthe same sequence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm_curve <- plot(km) +\n  scale_color_manual(values = c(All = \"steelblue\"), guide = \"none\") +\n  scale_fill_manual(values = c(All = \"steelblue\"), guide = \"none\") +\n  scale_x_continuous(breaks = seq(0, 20, 5)) +\n  scale_y_continuous(breaks = seq(0, 100, 20),\n                     labels = function(x) paste0(x, \"%\")) +\n  coord_cartesian(xlim = c(0, 20), ylim = c(0, 100)) +\n  labs(x = \"Years after operation\", y = \"Freedom from death (%)\") +\n  theme_hv_manuscript()\n\nkm_risk <- hv_atrisk(km)\nhv_atrisk_compose(km_curve, km_risk)\n```\n\n::: {.cell-output-display}\n![Kaplan-Meier survival with the supporting at-risk denominator aligned at 0, 5, 10, 15, and 20 years](figure_tables_files/figure-pdf/fig-tables-atrisk-1.pdf){#fig-tables-atrisk fig-pos='H'}\n:::\n:::\n\n\n## Longitudinal count table\n\n`hv_longitudinal()` produces a two-panel figure: a grouped bar chart of\nparticipation counts and a numeric table panel below it. The underlying\ncounts live in the object's `$data` slot in long format (one row per\ntime-window × series), with the column roles recorded in `$meta`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlc <- hv_longitudinal(sample_longitudinal_counts_data(n_patients = 300, seed = 42L))\nnames(lc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data\"   \"meta\"   \"tables\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlc$meta[c(\"x_col\", \"group_col\", \"count_col\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$x_col\n[1] \"time_label\"\n\n$group_col\n[1] \"series\"\n\n$count_col\n[1] \"count\"\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(lc$data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t14 obs. of  3 variables:\n $ time_label: Factor w/ 7 levels \"≥0 Days\",\"≥1 Month\",..: 1 2 3 4 5 6 7 1 2 3 ...\n $ series    : chr  \"Patients\" \"Patients\" \"Patients\" \"Patients\" ...\n $ count     : int  19 47 49 100 159 101 276 19 50 56 ...\n```\n\n\n:::\n:::\n\n\nWe reshape the long counts into a wide table (one row per follow-up\nwindow, one column per series) and render it with `gt`. This is the\ntabular companion to the bar chart's table panel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlc_wide <- lc$data |>\n  tidyr::pivot_wider(\n    names_from  = series,\n    values_from = count\n  )\nlc_wide\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 x 3\n  time_label Patients Measurements\n  <fct>         <int>        <int>\n1 ≥0 Days          19           19\n2 ≥1 Month         47           50\n3 ≥3 Months        49           56\n4 ≥6 Months       100          118\n5 ≥1 Year         159          217\n6 ≥2 Years        101          113\n7 ≥2.5 Years      276          620\n```\n\n\n:::\n\n```{.r .cell-code}\nlc_wide |>\n  gt(rowname_col = \"time_label\") |>\n  tab_header(\n    title    = \"Longitudinal Participation Counts\",\n    subtitle = \"Patients and measurements at each follow-up window\"\n  ) |>\n  fmt_number(columns = where(is.numeric), decimals = 0) |>\n  tab_stubhead(label = \"Follow-up window\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Longitudinal Participation Counts\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Patients and measurements at each follow-up window\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}l|rr}\n\\toprule\nFollow-up window & Patients & Measurements \\\\ \n\\midrule\\addlinespace[2.5pt]\n≥0 Days & 19 & 19 \\\\ \n≥1 Month & 47 & 50 \\\\ \n≥3 Months & 49 & 56 \\\\ \n≥6 Months & 100 & 118 \\\\ \n≥1 Year & 159 & 217 \\\\ \n≥2 Years & 101 & 113 \\\\ \n≥2.5 Years & 276 & 620 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nThe `gt` version above is for a standalone table, say in the manuscript body or\na supplement. When the numbers belong *inside* the figure, the package draws\nthem as a table panel you stack under the chart. For reference, the same counts\nrendered as the in-figure table panel appear below the bar chart when the two\nare composed with `patchwork`. Building both from the same `lc$data` keeps the\nstandalone table and the in-figure panel telling one story.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_bar <- plot(lc) +\n  scale_fill_manual(\n    values = c(Patients = \"steelblue\", Measurements = \"firebrick\"),\n    name   = NULL\n  ) +\n  labs(x = NULL, y = \"Count (n)\")\n\np_tbl <- plot(lc, type = \"table\") +\n  scale_colour_manual(\n    values = c(Patients = \"steelblue\", Measurements = \"firebrick\"),\n    guide  = \"none\"\n  )\n\np_bar / p_tbl + plot_layout(heights = c(3, 1))\n```\n\n::: {.cell-output-display}\n![](figure_tables_files/figure-pdf/lc_figure-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## Pitfalls\n\n- **At-risk counts must match the curve's time axis.** The risk strip is only\n  useful if its columns sit under the same time points the curve uses. If the\n  plot runs 0 to 20 years on a five-year grid, the at-risk table needs the same\n  grid, or the reader cannot line a count up with the part of the curve it\n  describes. Set `report_times` explicitly when you build `km`, use those times\n  as the curve's breaks, and let `hv_atrisk_compose()` align the finished\n  panels. If you later crop the curve, inspect the table again.\n- **Keeping the table and figure in sync.** The reason we pull numbers off the\n  plot object rather than recomputing them is to keep a single source of truth.\n  The moment you summarise the cohort separately for the table, the two can\n  drift: a filter applied to one and not the other, a different handling of\n  missing follow-up, a stale data load. If you must build a companion table by\n  hand, derive it from the exact frame the figure was built from, and re-derive\n  both whenever the data change. A figure and a table that disagree are worse\n  than either alone, because a reader cannot tell which to believe.\n",
    "supporting": [
      "figure_tables_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}