{
  "hash": "32f243aebd1e51c2793ff0b9bae76393",
  "result": {
    "engine": "knitr",
    "markdown": "# Which variables contribute to prediction?\n\n\n\n## When to use it\n\nOnce a forest predicts adequately, a co-author usually asks which variables\ncarry that prediction. Permutation variable importance (VIMP) answers by\nbreaking one predictor's information in the OOB data and measuring how much\nprediction error changes.\n\nThat is a model question. VIMP is not an effect size, does not give the\ndirection of association, and does not show that a variable causes the\noutcome. Correlated predictors can share predictive information, so permuting\none may redistribute or understate the importance we would see if it stood\nalone.\n\n## Fit a classification forest\n\nWe again use iris so the returned object exposes both global and class-specific\nVIMP. `importance = TRUE` asks `rfsrc()` to retain permutation importance. The\nbounded 300-tree fit is for teaching; a study analysis should verify both the\nerror trajectory and the ranking's stability across an adequate forest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260828)\nrf <- rfsrc(\n  Species ~ .,\n  data = iris,\n  ntree = 300,\n  importance = TRUE\n)\nrf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         Sample size: 150\n           Frequency of class labels: setosa=50, versicolor=50, virginica=50\n                     Number of trees: 300\n           Forest terminal node size: 1\n       Average no. of terminal nodes: 9.5433\nNo. of variables tried at each split: 2\n              Total no. of variables: 4\n       Resampling used to grow trees: swor\n    Resample size used to grow trees: 95\n                            Analysis: RF-C\n                              Family: class\n                      Splitting rule: gini *random*\n       Number of random split points: 10\n                   (OOB) Brier score: 0.02448324\n        (OOB) Normalized Brier score: 0.11017457\n                           (OOB) AUC: 0.9937\n                      (OOB) Log-loss: 0.12563704\n   (OOB) Requested performance error: 0.05333333, 0.02, 0.06, 0.08\n\nConfusion matrix:\n\n            predicted\n  observed   setosa versicolor virginica class.error\n  setosa         49          1         0        0.02\n  versicolor      0         47         3        0.06\n  virginica       0          4        46        0.08\n\n      (OOB) Misclassification rate: 0.05333333\n\nRandom-classifier baselines (uniform):\n   Brier: 0.22222222   Normalized Brier: 1   Log-loss: 1.09861229\n```\n\n\n:::\n:::\n\n\n## Build and inspect it\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvimp_dta <- gg_vimp(rf)\nvimp_dta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<gg_vimp>  from randomForestSRC  |  family: class  |  ntree: 300  |  n: 150  |  variables: 16\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(as.data.frame(vimp_dta), 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars        set      vimp positive\n1  Petal.Width versicolor 0.7846667     TRUE\n2 Petal.Length versicolor 0.6260000     TRUE\n3  Petal.Width        all 0.6187549     TRUE\n4  Petal.Width     setosa 0.5880000     TRUE\n5 Petal.Length        all 0.5177924     TRUE\n6 Petal.Length     setosa 0.4853333     TRUE\n7  Petal.Width  virginica 0.4626667     TRUE\n8 Petal.Length  virginica 0.4246667     TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nwith(as.data.frame(vimp_dta),\n     aggregate(vimp, list(outcome = set), max))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     outcome         x\n1        all 0.6187549\n2     setosa 0.5880000\n3 versicolor 0.7846667\n4  virginica 0.4626667\n```\n\n\n:::\n:::\n\n\nThe `vars` column holds raw predictor identities. `set = \"all\"` is the global\npermutation score; the named class sets show the one-vs-rest contribution for\neach outcome. Positive VIMP means permutation worsened prediction. Negative\nVIMP means permutation improved it in this fit, often a sign of noise or an\nunstable small contribution. The sign is not the direction of a clinical\nassociation.\n\n## Expect the numbers to move\n\nRun this chapter on your own machine and the VIMP values will not match the\nones printed here. That is not a seeding mistake, and it is worth knowing\nbefore you quote a number from a forest into a manuscript.\n\n`set.seed()` fixes the forest for a given machine, and it holds. What it does\nnot survive is a change of platform. Rebuilding the book on a Linux runner\nmoved petal width's global score from 0.619 to 0.633 and reordered the rows\nbeneath it, with the same seed, the same `randomForestSRC` version and the same\nR.\n\nWhat moves is the forest, not the importance calculation. The plainest evidence\nis [Did the forest stabilize?](rf_error.qmd), which grows the same iris\nforest on the same seed and never asks for importance at all, and whose\nout-of-bag error still shifts in the third decimal across the same two\nmachines. Nor is this a property of classification forests, since the\nclassification forest in [How well does the forest predict?](rf_roc.qmd)\nreproduces exactly.\n\nIt is this dataset. Of the eight forests in the book, the two grown on `iris`\nboth move across platforms and the other six, on `pbc`, `veteran`,\n`SynthDiabetes`, `breast`, `housing` and a simulated cohort, all reproduce to\nthe last decimal. `iris` is measured to the nearest millimetre, so its 150 rows\ncarry a great many exactly tied values, and a split has to break those ties\nsomehow. That is where we would look first, though we have not proved it.\n\nThe size of the shift is the useful part. Petal length and petal width sit far\nabove both sepal measurements in every run we have looked at, and that\nseparation is what @fig-rf_vimp is for. The order *within* a close pair is not,\nat 300 trees. So read the grouping rather than the ranking. If an analysis\ngenuinely needs the ranking, grow the forest until the ranking stops moving,\nand report how many trees that took.\n\n## Use display labels at plot time\n\nHuman-readable labels belong in the display, not in the model object. The\ncurrent plot method uses `labels`. We confirm that applying those labels leaves\nthe returned variables and their order unchanged.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_labels <- c(\n  Sepal.Length = \"Sepal length\",\n  Sepal.Width = \"Sepal width\",\n  Petal.Length = \"Petal length\",\n  Petal.Width = \"Petal width\"\n)\n\nraw_ids <- as.character(vimp_dta$vars)\nvimp_plot <- plot(vimp_dta, labels = feature_labels)\n\ndata.frame(\n  raw_names_unchanged = identical(raw_ids, as.character(vimp_dta$vars)),\n  rows = nrow(vimp_dta),\n  outcome_sets = length(unique(vimp_dta$set))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  raw_names_unchanged rows outcome_sets\n1                TRUE   16            4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvimp_plot +\n  geom_hline(yintercept = 0, color = \"grey45\", linewidth = 0.35) +\n  theme_hv_manuscript() +\n  scale_y_continuous(\n    breaks = function(x) pretty(x, n = 3),\n    expand = expansion(mult = c(0.05, 0.05))\n  ) +\n  labs(x = \"Predictor\", y = \"Permutation VIMP\", fill = \"VIMP > 0\") +\n  theme(axis.text.x = element_text(size = 7))\n```\n\n::: {.cell-output-display}\n![Permutation VIMP overall and by iris class; display labels do not alter the stored predictor names](rf_vimp_files/figure-pdf/fig-rf_vimp-1.pdf){#fig-rf_vimp fig-pos='H'}\n:::\n:::\n\n\n## Read it\n\nStart with the `all` facet for the global ranking, then inspect whether the\nclass-specific facets tell the same story. Petal width and petal length carry\nmost of the prediction in this fit. A predictor can rank differently by class\nbecause the forest may need it to distinguish one outcome more than another.\nThe grey zero line separates positive from negative VIMP, and the axis range is\nset from the returned scores so neither negative values nor larger positive\nvalues are clipped.\n\nThe object contains point estimates, not confidence intervals. Small gaps near\nthe bottom should not be treated as settled ranks. If the order matters to a\nmanuscript conclusion, refit across seeds or use a resampling analysis and\nreport that uncertainty separately.\n\n## Adapt it\n\nFor a survival or regression forest there is usually one outcome set. For a\nclassification forest, inspect `unique(vimp_dta$set)` before deciding whether\nto report the global ranking or a class-specific one. `gg_vimp(rf, nvar = 10)`\ncan reduce a long display, but keep the full ranking in a supplement when the\ncutoff affects interpretation.\n\n## Pitfalls\n\n- **Reading sign as clinical direction.** Positive VIMP means worse prediction\n  after permutation, not that larger predictor values increase risk.\n- **Calling VIMP an effect size.** Scores depend on this forest, this outcome,\n  this predictor set, and the prediction-error scale.\n- **Ignoring correlated predictors.** Shared information can be split or\n  redistributed across variables.\n- **Treating labels as data changes.** Use `labels` in `plot()`. Keep the raw\n  predictor names intact for downstream code and audit trails.\n- **Claiming causality.** VIMP describes predictive contribution. It does not\n  identify an intervention effect.\n",
    "supporting": [
      "rf_vimp_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}