{
  "hash": "24ffef53dcc94d9304f035fd2ca7dbb3",
  "result": {
    "engine": "knitr",
    "markdown": "# Publication tables\n\nFor a thorough treatment of effective display tables in `gt` [@R-gt], see\nRich Iannone's guide:\n<https://rich-iannone.github.io/gt-effective-display-tables/>.\n\n\n\nUse `gt` when the finished table belongs in HTML or in this book. If the same\nnumbers are headed for a CORR or JTCVS Word manuscript, use\n[manuscript tables](hv_tables.qmd) instead.\n\nThis chapter builds the table by hand, directly with `gt`. That is worth\ndoing for two reasons. Assembling a Table 1 a row group at a time is how\nyou learn what is actually in one: which variables earn a row, which\nsummary each variable type asks for, and where a reader expects the\ndenominators. And `gt` is the right tool when the table's destination is\nan HTML document, this book included, rather than a Word file bound for a\njournal.\n\nThat splits the work along a clean line: hand-built `gt` for understanding and\nfor the web, and `hvtiRtables` when it goes to a manuscript.\n\n## When to use it\n\nOpen almost any clinical manuscript and the first table you meet is a\nbaseline-characteristics summary, the one journals number \"Table 1.\" It\ndescribes who was in the study before any outcome is discussed: how old the\npatients were, how their risk factors split, and whether the comparison groups\nlooked alike at the start. Reach for it whenever you need to convince a reader\nthat two arms are comparable, or simply to put a face on the cohort a figure\nlater summarises. The job is description, not inference. A good Table 1 lets a\nreader decide for themselves whether a later result is believable, because they\ncan see what the groups were made of.\n\nThe layout is always the same: rows of characteristics, columns split by the\ngrouping variable (treatment, exposure, sex). Continuous variables get a centre\nand a spread (mean and standard deviation, or median and interquartile range);\ncategorical variables get a count and a percentage. We build the table here from\n`hvtiRutilities::generate_survival_data()`, which returns a richly labelled\npatient-level cohort with a natural grouping variable (`sex`), so the recipe\nruns end to end before you point it at your own data. It is the same cohort\n[describing a dataset](data_tables.qmd) took inventory of, so if you want to see\nwhere the variables below came from, that chapter is one click back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndta <- hvtiRutilities::generate_survival_data(n = 200, seed = 42)\nstr(dta[, c(\"sex\", \"age\", \"bmi\", \"gfr_bs\", \"diabetes\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t200 obs. of  5 variables:\n $ sex     : Factor w/ 2 levels \"Female\",\"Male\": 2 2 1 2 1 2 1 2 2 2 ...\n  ..- attr(*, \"label\")= chr \"Sex\"\n $ age     : num  65.6 36.5 50.4 54.5 51.1 43.4 67.7 43.6 75.3 44.1 ...\n  ..- attr(*, \"label\")= chr \"Age at surgery (years)\"\n $ bmi     : num  27 30.8 27.2 30.7 26.3 26.7 29.4 32 20.8 26.8 ...\n  ..- attr(*, \"label\")= chr \"Body mass index (kg/m2)\"\n $ gfr_bs  : num  62 54.9 64.3 72.8 87 83.3 72.9 57.9 97.5 93.3 ...\n  ..- attr(*, \"label\")= chr \"Baseline eGFR (mL/min/1.73m2)\"\n $ diabetes: Factor w/ 2 levels \"No\",\"Yes\": 1 1 1 2 1 1 1 2 1 1 ...\n  ..- attr(*, \"label\")= chr \"Diabetes mellitus\"\n```\n\n\n:::\n:::\n\n\n## Build it\n\nA Table 1 is assembled one variable type at a time, then joined and rendered.\nWe summarise the continuous variables first, the categorical variable second,\nand hand the combined frame to `gt()` for formatting. Doing it in pieces keeps\neach summary readable and lets you check the numbers before they are dressed up.\n\n### Summarise numeric variables as mean ± SD\n\nWe summarise three continuous baseline variables (age, BMI, baseline\neGFR) as mean and standard deviation within each `sex` group. Mean and SD are\nthe textbook pair when a variable is roughly symmetric; for a skewed\nvariable (cost, time on bypass) you would report median and interquartile range\ninstead, since a mean dragged by a long tail misrepresents the typical patient.\n\nKnow before you copy this that mean and SD are not what a CORR manuscript table\nreports. The house convention is a median with the 15th and 85th percentiles,\nwhatever the shape, so that one summary covers the symmetric and the skewed\nvariable alike and there is no per-variable normality call to defend to a\nreviewer. [Manuscript tables](hv_tables.qmd) builds the table that way and\nprints the footnote that documents it. We stay with mean and SD here because\nthis chapter is assembling a table by hand for the web, and because holding the\ntwo conventions side by side is the fastest way to see what the house one buys\nyou.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_summary <- dta |>\n  group_by(sex) |>\n  summarise(\n    n        = dplyr::n(),\n    age_mean = mean(age),     age_sd = sd(age),\n    bmi_mean = mean(bmi),     bmi_sd = sd(bmi),\n    gfr_mean = mean(gfr_bs),  gfr_sd = sd(gfr_bs),\n    .groups  = \"drop\"\n  )\nnum_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 8\n  sex        n age_mean age_sd bmi_mean bmi_sd gfr_mean gfr_sd\n  <fct>  <int>    <dbl>  <dbl>    <dbl>  <dbl>    <dbl>  <dbl>\n1 Female    77     45.1   14.8     27.1   4.89     76.6   20.5\n2 Male     123     44.3   14.5     26.6   4.67     75.9   18.7\n```\n\n\n:::\n:::\n\n\n### Summarise a categorical variable as n (%)\n\nDiabetes status is summarised as a count and within-group percentage. The\npercentage here is *within* each sex group, the column denominator, which is\nalmost always what a reader expects: \"what fraction of the women had diabetes,\"\nnot \"what fraction of all diabetics were women.\" Make the denominator explicit\nin your own head before you compute it, because the same count divided by a\ndifferent base tells a different story.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_summary <- dta |>\n  group_by(sex) |>\n  summarise(\n    diabetes_n   = sum(diabetes == \"Yes\"),\n    diabetes_pct = 100 * mean(diabetes == \"Yes\"),\n    .groups      = \"drop\"\n  )\ncat_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 3\n  sex    diabetes_n diabetes_pct\n  <fct>       <int>        <dbl>\n1 Female         17         22.1\n2 Male           38         30.9\n```\n\n\n:::\n:::\n\n\n### Render with `gt()`\n\nWe join the two summaries and present the result with a header, relabelled\ncolumns, and consistent numeric formatting. Mean ± SD pairs are formatted\nto one decimal place; the diabetes percentage to one decimal place.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable1 <- num_summary |>\n  left_join(cat_summary, by = \"sex\") |>\n  gt(rowname_col = \"sex\") |>\n  tab_header(\n    title    = \"Table 1. Baseline Characteristics by Sex\",\n    subtitle = \"Simulated cohort, n = 200\"\n  ) |>\n  cols_label(\n    n            = \"N\",\n    age_mean     = \"Age (mean)\",\n    age_sd       = \"Age (SD)\",\n    bmi_mean     = \"BMI (mean)\",\n    bmi_sd       = \"BMI (SD)\",\n    gfr_mean     = \"eGFR (mean)\",\n    gfr_sd       = \"eGFR (SD)\",\n    diabetes_n   = \"Diabetes (n)\",\n    diabetes_pct = \"Diabetes (%)\"\n  ) |>\n  fmt_number(\n    columns  = c(age_mean, age_sd, bmi_mean, bmi_sd,\n                 gfr_mean, gfr_sd, diabetes_pct),\n    decimals = 1\n  ) |>\n  tab_spanner(label = \"Age (years)\",  columns = c(age_mean, age_sd)) |>\n  tab_spanner(label = \"BMI (kg/m²)\",  columns = c(bmi_mean, bmi_sd)) |>\n  tab_spanner(label = \"eGFR (mL/min)\", columns = c(gfr_mean, gfr_sd))\n\ntable1\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Table 1. Baseline Characteristics by Sex\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Simulated cohort, n = 200\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}l|rrrrrrrrr}\n\\toprule\n &  & \\multicolumn{2}{c}{{Age (years)}} & \\multicolumn{2}{c}{{BMI (kg/m²)}} & \\multicolumn{2}{c}{{eGFR (mL/min)}} &  &  \\\\ \n\\cmidrule(lr){3-4} \\cmidrule(lr){5-6} \\cmidrule(lr){7-8}\n & N & Age (mean) & Age (SD) & BMI (mean) & BMI (SD) & eGFR (mean) & eGFR (SD) & Diabetes (n) & Diabetes (\\%) \\\\ \n\\midrule\\addlinespace[2.5pt]\nFemale & 77 & 45.1 & 14.8 & 27.1 & 4.9 & 76.6 & 20.5 & 17 & 22.1 \\\\ \nMale & 123 & 44.3 & 14.5 & 26.6 & 4.7 & 75.9 & 18.7 & 38 & 30.9 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nThe table renders as static HTML here, which is what `gt` is for. When the same\nnumbers have to reach a journal, hand the summary to\n[manuscript tables](hv_tables.qmd) instead and let `hvtiRtables` place the\nfootnotes and the abbreviation key where the CORR rules want them.\n\n## Pitfalls\n\n- **Significance tests in Table 1.** It is tempting to add a p-value column\n  comparing the groups, and many journals still ask for one. In a randomised\n  trial that column is close to meaningless: any baseline difference is by\n  construction due to chance, so testing it asks whether randomisation worked,\n  not whether the groups differ in a way that matters. In an observational\n  cohort the test is at least answering a real question, but a small p-value on\n  a tiny clinically irrelevant difference (a half-year age gap in 5,000\n  patients) misleads more than it informs. Describe the groups; let the reader\n  judge balance from the numbers and the standardised differences.\n- **Inconsistent rounding.** Decide on decimal places per variable and hold to\n  it down the whole column. Age to one decimal in one row and whole numbers in\n  the next reads as carelessness and makes the eye work harder. `fmt_number()`\n  with a fixed `decimals` keeps a column honest; the recipe above pins the\n  continuous summaries and the percentage to one decimal each.\n- **Ambiguous denominators for percentages.** A percentage means nothing\n  without its base. State whether it is computed within the column group, across\n  the whole cohort, or among only the patients with a non-missing value, and be\n  consistent. When missingness is common, report the n the percentage rests on\n  so a reader does not assume a denominator you did not use.\n",
    "supporting": [
      "qt_tables_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"t1_gt\",\"t1_gt\",\"t1_gt\",\"t1_gt\",\"t1_gt\",\"t1_gt\",\"t1_gt\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}